# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
#[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[character]

success_symbol = "[シ](bold purple) "
error_symbol = "[メ](bold red) "
vicmd_symbol = "[か] (bold blue)"
format ="""$symbol"""

[directory]
format ="""[メ](bold blue)[$path](bold purple)[❯](bold blue)[❯](bold green)[❯](bold blue)[$read_only]($read_only_style)"""
read_only = "λ"
read_only_style = "bold red"
